services:
  postgres:
    container_name: shopdb
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shop'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5532:5432'
